CREATE TABLE `on_mtg_db`.`ACCOUNT`
	(`ID` VARCHAR(10), 
	`F_NAME` VARCHAR(20), 
	`L_NAME` VARCHAR(20), 
	`ADDRESS` VARCHAR(60), 
	`CITY` VARCHAR(15), 
	`BRANCH` VARCHAR(15), 
	`ZIP` VARCHAR(8), 
	`USERNAME` VARCHAR(20), 
	`PASSWORD` VARCHAR(30), 
	`PHONE` VARCHAR(15), 
	`EMAIL` VARCHAR(30), 
	`ACCOUNT_TYPE` VARCHAR(15), 
	`REG_DATE` VARCHAR(15)
   );