
CREATE TABLE `on_mtg_db`.`LOAN` 
   (`ID` VARCHAR(10), 
	`AMOUNT` DECIMAL(38,0), 
	`STATUS` VARCHAR(8), 
	`FIRST_NAME` VARCHAR(20), 
	`LAST_NAME` VARCHAR(20), 
	`ADDRESS` VARCHAR(60), 
	`EMAIL` VARCHAR(30)
   );
